# Força máxima no sinal (CRUCIAL para parar de travar)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Ajuste de Debounce (Remove repetição de teclas)
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=7
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=7
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# JOYSTICK
CONFIG_GPIO=y

# Ativa driver da tela
CONFIG_ZMK_DISPLAY=y

# Habilita RGB Underglow
CONFIG_ZMK_RGB_UNDERGLOW=y

# (Opcional) Desliga o RGB quando o teclado não está sendo usado para economizar bateria
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
